TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

INCLUDEPATH += \
D:/docs/huya_gitlab/videoProxy/rsfec

SOURCES += \
        main.cpp \
    main.cpp \
    main.cpp \
    pacing_controller.cc \
    modules/pacing/pacing_controller.cc \
    main.cpp \
    modules/pacing/pacing_controller.cc \
    main.cpp \
    modules/pacing/pacing_controller.cc \
    main.cpp \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    main.cpp \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    main.cpp \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    main.cpp \
    fecqueue.cc \
    modules/fec/fecqueue.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    main.cpp \
    modules/fec/rsfecsender.cc \
    modules/fec/fecqueue.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    main.cpp \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    system_wrappers/include/clock.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/fec/interleaving_util.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/fec/fec_generator.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/video_coding/nack_responder.cc \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    modules/video_coding/nack_responder.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.cc \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    modules/video_coding/nack_responder.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    api/transport/network_types.cc \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.cc \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    modules/video_coding/nack_responder.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/fec/loss_pattern_analyze.cc \
    modules/congestion_controller/goog_cc/goog_cc_network_control.cc \
    modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.cc \
    api/transport/network_types.cc \
    api/units/data_rate.cc \
    api/units/time_delta.cc \
    api/units/timestamp.cc \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.cc \
    modules/congestion_controller/goog_cc/goog_cc_network_control.cc \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.cc \
    modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/loss_pattern_analyze.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/video_coding/nack_requester.cc \
    modules/video_coding/nack_responder.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/video_coding/jitterbuffer.cpp \
    modules/congestion_controller/goog_cc/inter_arrival_delta.cc \
    modules/congestion_controller/goog_cc/delay_based_bwe.cc \
    api/transport/network_types.cc \
    api/units/data_rate.cc \
    api/units/time_delta.cc \
    api/units/timestamp.cc \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.cc \
    modules/congestion_controller/goog_cc/delay_based_bwe.cc \
    modules/congestion_controller/goog_cc/goog_cc_network_control.cc \
    modules/congestion_controller/goog_cc/inter_arrival_delta.cc \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.cc \
    modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.cc \
    modules/congestion_controller/goog_cc/trendline_estimator.cc \
    modules/fec/fec_generator.cc \
    modules/fec/fecqueue.cc \
    modules/fec/interleaving_util.cc \
    modules/fec/loss_pattern_analyze.cc \
    modules/fec/rsfecsender.cc \
    modules/pacing/pacing_controller.cc \
    modules/pacing/prioritized_packet_queue.cc \
    modules/remote_bitrate_estimator/aimd_rate_control.cc \
    modules/video_coding/jitterbuffer.cpp \
    modules/video_coding/nack_requester.cc \
    modules/video_coding/nack_responder.cc \
    system_wrappers/include/clock.cc \
    main.cpp \
    modules/remote_bitrate_estimator/overuse_detector.cc \
    modules/congestion_controller/goog_cc/link_capacity_estimator.cc \
    modules/congestion_controller/goog_cc/mycc.cc

HEADERS += \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    pacing_controller.h \
    timestamp.h \
    time_delta.h \
    clock.h \
    unit_base.h \
    data_size.h \
    api/units/data_size.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    pacing_controller.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    pacing_controller.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/pacing/pacing_controller.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/round_robin_packet_queue.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    fecqueue.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    modules/fec/fecqueue.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    protocol.h \
    task_queue_paced_sender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fecqueue.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    rtc_base/units/unit_base.h \
    system_wrappers/include/clock.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fecqueue.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    protocol.h \
    task_queue_paced_sender.h \
    system_wrappers/include/ntp_time.h \
    modules/fec/interleaving_util.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    modules/fec/fec_generator.h \
    modules/fec/rsfec_resender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    rtc_base/numerics/sequence_number_util.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    modules/video_coding/nack_responder.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    modules/video_coding/nack_responder.h \
    rtc_base/numerics/sequence_number_util.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.h \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    modules/video_coding/nack_responder.h \
    rtc_base/numerics/sequence_number_util.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    api/transport/network_types.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.h \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    modules/video_coding/nack_responder.h \
    rtc_base/numerics/sequence_number_util.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    modules/fec/loss_pattern_analyze.h \
    modules/congestion_controller/goog_cc/goog_cc_network_control.h \
    modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.h \
    modules/congestion_controller/goog_cc/packets_delay_estimation.h \
    api/transport/network_types.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.h \
    modules/congestion_controller/goog_cc/goog_cc_network_control.h \
    modules/congestion_controller/goog_cc/packets_delay_estimation.h \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.h \
    modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/loss_pattern_analyze.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    modules/video_coding/nack_responder.h \
    rtc_base/numerics/sequence_number_util.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    modules/congestion_controller/goog_cc/inter_arrival_delta.h \
    modules/congestion_controller/goog_cc/delay_based_bwe.h \
    api/transport/network_types.h \
    api/units/data_rate.h \
    api/units/data_size.h \
    api/units/frequency.h \
    api/units/time_delta.h \
    api/units/timestamp.h \
    api/network_state_predictor.h \
    modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.h \
    modules/congestion_controller/goog_cc/delay_based_bwe.h \
    modules/congestion_controller/goog_cc/goog_cc_network_control.h \
    modules/congestion_controller/goog_cc/inter_arrival_delta.h \
    modules/congestion_controller/goog_cc/packets_delay_estimation.h \
    modules/congestion_controller/goog_cc/robust_throughput_estimator.h \
    modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.h \
    modules/congestion_controller/goog_cc/trendline_estimator.h \
    modules/fec/fec_generator.h \
    modules/fec/fecqueue.h \
    modules/fec/interleaving_util.h \
    modules/fec/loss_pattern_analyze.h \
    modules/fec/rsfec_resender.h \
    modules/fec/rsfecsender.h \
    modules/fec/video_fec_generator.h \
    modules/include/module_common_types.h \
    modules/pacing/pacing_controller.h \
    modules/pacing/prioritized_packet_queue.h \
    modules/pacing/round_robin_packet_queue.h \
    modules/remote_bitrate_estimator/aimd_rate_control.h \
    modules/rtp_rtcp/include/rtp_rtcp_defines.h \
    modules/rtp_rtcp/source/rtp_packet.h \
    modules/rtp_rtcp/source/rtp_packet_to_send.h \
    modules/video_coding/nack_requester.h \
    modules/video_coding/nack_responder.h \
    rtc_base/numerics/sequence_number_util.h \
    rtc_base/units/unit_base.h \
    rtc_base/time_utils.h \
    system_wrappers/include/clock.h \
    system_wrappers/include/ntp_time.h \
    protocol.h \
    task_queue_paced_sender.h \
    modules/remote_bitrate_estimator/overuse_detector.h \
    modules/congestion_controller/goog_cc/link_capacity_estimator.h
